// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          int                `json:"id"`
	PostID      int                `json:"postID"`
	ContentMeta *ContentMeta       `json:"contentMeta"`
	Content     string             `json:"content"`
	Replies     *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor int      `json:"cursor"`
	Node   *Comment `json:"node"`
}

type ContentMeta struct {
	Author      string `json:"author"`
	PublishedAt string `json:"publishedAt"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   int  `json:"endCursor"`
	HasNextPage bool `json:"hasNextPage"`
}

type Post struct {
	ID              int          `json:"id"`
	Title           string       `json:"title"`
	ContentMeta     *ContentMeta `json:"contentMeta"`
	Content         string       `json:"content"`
	CommentsEnabled bool         `json:"commentsEnabled"`
}

type PostSnippet struct {
	PostID         int          `json:"postID"`
	Title          string       `json:"title"`
	ContentMeta    *ContentMeta `json:"contentMeta"`
	ContentSnippet string       `json:"contentSnippet"`
}

type PostSnippetConnection struct {
	Edges    []*PostSnippetEdge `json:"edges"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type PostSnippetEdge struct {
	Cursor int          `json:"cursor"`
	Node   *PostSnippet `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
