// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          string       `json:"id"`
	PostID      string       `json:"postId"`
	ParentID    *string      `json:"parentId,omitempty"`
	ContentMeta *ContentMeta `json:"contentMeta"`
	Content     string       `json:"content"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type ContentMeta struct {
	Author      *User  `json:"author"`
	PublishedAt string `json:"publishedAt"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type Post struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	ContentMeta     *ContentMeta       `json:"contentMeta"`
	Content         string             `json:"content"`
	CommentsEnabled bool               `json:"commentsEnabled"`
	Comments        *CommentConnection `json:"comments"`
}

type PostSnippet struct {
	PostID         string       `json:"postId"`
	Title          string       `json:"title"`
	ContentMeta    *ContentMeta `json:"contentMeta"`
	ContentSnippet string       `json:"contentSnippet"`
}

type PostSnippetConnection struct {
	Edges    []*PostSnippetEdge `json:"edges"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type PostSnippetEdge struct {
	Cursor string       `json:"cursor"`
	Node   *PostSnippet `json:"node"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
